const friendsData = {
	friend1: {
		username: 'Mark Webber',
		avatar: './images/avatar-mark-webber.webp',
		description: 'reacted to your recent post',
		myPost: 'My first tornament today!',
		myGroup: '',
		myPicture: '',
		updatedTime: '1m',
	},
	friend2: {
		username: 'Angela Gray',
		avatar: './images/avatar-angela-gray.webp',
		description: 'followed you',
		myPost: '',
		myGroup: '',
		myPicture: '',
		updatedTime: '5m',
	},
	friend3: {
		username: 'Jacob Thompson',
		avatar: './images/avatar-jacob-thompson.webp',
		description: 'has join your group',
		myPost: '',
		myGroup: 'Chess Club',
		myPicture: '',
		updatedTime: '1 day',
	},
	friend4: {
		username: 'Rizky Hasanuddlin',
		avatar: './images/avatar-rizky-hasanuddin.webp',
		description: 'sent you a private message',
		myPost: '',
		myGroup: '',
		myPicture: '',
		updatedTime: '5 days',
	},
	friend5: {
		username: 'Kimberly Smith',
		avatar: './images/avatar-kimberly-smith.webp',
		description: 'commented on your picture',
		myPost: '',
		myGroup: '',
		myPicture: '<img src="./images/image-chess.webp">',
		updatedTime: '1 week',
	},
	friend6: {
		username: 'Nathan Peterson',
		avatar: './images/avatar-nathan-peterson.webp',
		description: 'reacted to your recent post',
		myPost: '5 end-game strategies to increae your win rate',
		myGroup: '',
		myPicture: '',
		updatedTime: '2 weeks',
	},
	friend7: {
		username: 'Anna Kim',
		avatar: './images/avatar-anna-kim.webp',
		description: 'left your group',
		myPost: '',
		myGroup: 'Chess Club',
		myPicture: '',
		updatedTime: '2 weeks',
	},
};

export { friendsData };
